
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge
gems:                [jekyll-paginate]


permalink:           /:title


# Setup
timezone:            America/New_York # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Tangles & Twists
title:               Tangles & Twists
tagline:             'Literature, macrame, travel ... all in one blog'
description:         'Welcome to my Tangles & Twists blog, where I cover all the things I love.'
url:                 https://tanglesandtwists.github.io
rss:                 
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                / # /assets/img/icon.png [best 300px X 300px]
disqus:              tanglesandtwists # get it on https://disqus.com/admin/

author:
  name:           	 Leah Segal
  url:            	 https://TanglesAndTwists.github.io
  facebook:          profile.php?id=100009141895784&ref=br_tf
  twitter:           segall2015
  linkedin:          leah-segal-aa554a156
  pinterest:         leahsegal15
  instagram:         leah.creative


fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001


defaults:
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      layout: "default"
      author: "Leah Segal"
      permalink: /:categories/:month/:day/:year/:title.html
      comments: true